Add verifier
iden3/rapidsnark pull request #12
Opened 2024-02-05 21:40 UTC by nixw4

2024-02-06 09:17 UTC, olomix approved these changes

2024-02-06 09:17 UTC, olomix commented on src/verifier.h
> +#define VERIFIER_VALID_PROOF        0x0
As it is a C header without C++ namespacing, I would add GROTH16_ prefix to these constant. But as counterpart PROOF_ error codes do not have this prefix, may be such naming is OK too 🤷

2024-02-06 09:35 UTC, olomix requested changes
It doesn't work properly.
We have a test case where we generate proof using cmd `prover`, then validate this proof with `snarkjs`.
https://github.com/iden3/rapidsnark/blob/5af1b046bbce9c56921a1f105015ed9bb31b62f4/.github/workflows/build.yml#L139

I've also generated a proof on my laptop. Tried to validate it at got the OK result
```
package_macos_arm64/bin/verifier proof.json public.json testdata/verification_key.json
Result: Valid proof
```

Then I modified the public.json file, rerun the command
```
$ package_macos_arm64/bin/verifier proof.json public.json testdata/verification_key.json
Result: Valid proof
```
and still got an OK result. While the snarkjs is returning error on modified public.json.

2024-02-20 07:42 UTC, olomix approved these changes

2024-02-22 22:27 UTC, OBrezhniev approved these changes

2024-02-23 08:14 UTC, merged